appName: JiraMetricsEazybi

#Public report url of eazybi to extract data from, should have issues with their cycletimes
#Header of the table should be "Data, Key, Issuetype, cycletime"
Report_URL: https://aod.eazybi.com/accounts/70597/export/report/1075966-api-export.csv?embed_token=sclpf5w7ym8suuxzbop5hcn60f03eev6ht4346up4ydplyd3qaavol6it1mp

# Issuetype
# Custom issuetypes, right now you can't change the 3 types: Story, Bug, Task, but you can assign the custom names to main ones
Issuetype:
    Story: História
    Bug: Bug
    Task: Tarefa

# Cycletime
# Percentiles - Cycletime percentiles that the script should return as columns
Cycletime:
    Percentiles:
        - 50
        - 85
        - 95

# Monte Carlo Simulation
# Simulations - how many simulations we should run, 10k should give you a good result
# Simulation Days - Quantity of days to be added as a parameter of the simulation, result will be how many items will fit this timebox
# Percentiles - that the script should return, the script will return the nearest neighbor result
Montecarlo:
    Simulations: 10000
    Simulation_days: 14
    Percentiles:
        - 50
        - 85
        - 95
